In [2]:
import numpy

a = numpy.array([1,2,3,4], float)
b = numpy.array([5,6,7,8], float)

print(a + b)                     #[  6.   8.  10.  12.]
print(numpy.add(a, b))           #[  6.   8.  10.  12.]

print(a - b)                     #[-4. -4. -4. -4.]
print(numpy.subtract(a, b))      #[-4. -4. -4. -4.]

print(a * b)                     #[  5.  12.  21.  32.]
print(numpy.multiply(a, b))      #[  5.  12.  21.  32.]

print(a / b)                   #[ 0.2         0.33333333  0.42857143  0.5       ]
print(numpy.divide(a, b))        #[ 0.2         0.33333333  0.42857143  0.5       ]

print(a % b)                     #[ 1.  2.  3.  4.]
print(numpy.mod(a, b))           #[ 1.  2.  3.  4.]

print(a**b)                      #[  1.00000000e+00   6.40000000e+01   2.18700000e+03   6.55360000e+04]
print(numpy.power(a, b))         #[  1.00000000e+00   6.40000000e+01   2.18700000e+03   6.55360000e+04]


[ 6.  8. 10. 12.]
[ 6.  8. 10. 12.]
[-4. -4. -4. -4.]
[-4. -4. -4. -4.]
[ 5. 12. 21. 32.]
[ 5. 12. 21. 32.]
[0.2        0.33333333 0.42857143 0.5       ]
[0.2        0.33333333 0.42857143 0.5       ]
[1. 2. 3. 4.]
[1. 2. 3. 4.]
[1.0000e+00 6.4000e+01 2.1870e+03 6.5536e+04]
[1.0000e+00 6.4000e+01 2.1870e+03 6.5536e+04]


In [4]:
ab_start, a, b = input().split("\n")

In [5]:
ab_start

'1 4'

In [6]:
a

'1 2 3 4'

In [7]:
b

'5 6 7 8'

In [11]:
import numpy as np

n, m = map(int, input().split())
A = []
B = []

for i in range(n):
    A.append([*map(int, input().split())])
A = np.array(A)

for j in range(n):
    B.append(list(map(int, input().split())))
B = np.array(B)

print(np.add(A, B))
print(A - B)
print(np.multiply(A, B))
print(np.floor_divide(A, B))
print(A % B)
print(A ** B)

ValueError: too many values to unpack (expected 2)

In [13]:
import pandas as pd

data = pd.DataFrame({"k1": ["one", "two"] * 3 + ["two"],"k2": [1, 1, 2, 3, 3, 4, 4]})


In [16]:
data.duplicated().value_counts()

False    6
True     1
Name: count, dtype: int64