In [9]:
import numpy as np
np.set_printoptions(legacy='1.13')


In [10]:
print(np.identity(3)) #3 is for  dimension 3 X 3

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [11]:
print(np.eye(8, 7, k = 1))

[[ 0.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]]


In [12]:
print(np.eye(8, 7, k = -2))

[[ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.]]


In [27]:
rows,columns = input().split(" ")
row = int(rows)
columns = int(columns)

In [34]:
matrix = np.zeros((row,columns)).astype(int)


In [36]:
for x in matrix:
    x += 1



In [37]:
matrix

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])