# Array Creation

In [2]:
import numpy as np
import math


In [3]:
a = np.array([1,2,3])
print(a)
print(a.ndim)

[1 2 3]
1


In [4]:
b = np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
b.shape

(2, 3)

In [6]:
b.dtype

dtype('int64')

In [8]:
c = np.array([2.2, 5, 1.1])
c.dtype.name

'float64'

In [9]:
c

array([2.2, 5. , 1.1])

In [10]:
d = np.zeros((2,3))
print(d)

e = np.ones((2,3))
print(e)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [11]:
np.random.rand(2,3)

array([[0.50615877, 0.58333024, 0.01909288],
       [0.46456742, 0.30105961, 0.90405971]])

In [14]:
f = np.arange(10,50,2)
f

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [15]:
np.linspace(0,2,15)

array([0.        , 0.14285714, 0.28571429, 0.42857143, 0.57142857,
       0.71428571, 0.85714286, 1.        , 1.14285714, 1.28571429,
       1.42857143, 1.57142857, 1.71428571, 1.85714286, 2.        ])

## Array Operations

In [19]:
a = np.array([10,20,30,40])
b = np.array([1,2,3,4])

c = a-b
print(c)

d = a*b
print(d)

[ 9 18 27 36]
[ 10  40  90 160]


In [22]:
farenheit = np.array([0, -10, -5, -15, 0])

# The formula conversion to degrees: ((F - 32) x 5/9 = C)
celcius = (farenheit - 31) * (5/9)
celcius

array([-17.22222222, -22.77777778, -20.        , -25.55555556,
       -17.22222222])

In [23]:
celcius > -20

array([ True, False, False, False,  True])

In [25]:
celcius % 2 == 0

array([False, False,  True, False, False])

In [26]:
A = np.array([[1,1],[0,1]])
B = np.array([[2,0],[3,4]])
print(A*B)

[[2 0]
 [0 4]]


In [28]:
# matrix product
print(A@B)

[[5 4]
 [3 4]]


In [30]:
# Linear algebra concepts

A.shape

(2, 2)

In [35]:
array1 = np.array([[1,2,3],[4,5,6]])
print(array1.dtype)

array2 = np.array([[7.1,8.2,9.1],[10.4,11.2,12.3]])
print(array2.dtype)

int64
float64


In [36]:
array3 = array1 + array2
print(array3)
print(array3.dtype)


[[ 8.1 10.2 12.1]
 [14.4 16.2 18.3]]
float64


In [38]:
print(array3.sum())
print(array3.mean())
print(array3.min())
print(array3.max())

79.3
13.216666666666667
8.1
18.3


In [40]:
b = np.arange(1,16,1).reshape(3,5)
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

# Index, Slicing and Iterating

In [45]:
a = np.array([1,3,5,7])
print(a[2])

5


In [46]:
a = np.array([[1,2],[3,4],[5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [48]:
print(a[1,1])

4


In [50]:
np.array([a[0,0], a[1,1], a[2,1]])

array([1, 4, 6])

In [51]:
print(a[[0,1,2],[0,1,1]])

[1 4 6]


# Boolean Indexing

In [53]:
print(a > 5)

[[False False]
 [False False]
 [False  True]]


In [54]:
print(a[a>5])

[6]


# Slicing

In [56]:
a = np.array([0,1,2,3,4,5])

In [57]:
print(a[:3])

[0 1 2]


In [58]:
print(a[2:4])

[2 3]


In [61]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [62]:
a[:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [63]:
a[:2, 1:3]

array([[2, 3],
       [6, 7]])

In [67]:
sub_array = a[:2, 1:3]
print("sub array index [0,0] value before change:", sub_array[0,0])
sub_array[0,0] = 50
print("sub array index [0,0] value after change:", sub_array[0,0])
print("original array index [0,1] value after change:", a[0,1])





sub array index [0,0] value before change: 2
sub array index [0,0] value after change: 50
original array index [0,1] value after change: 50


In [1]:
from itertools import combinations
from math import comb as ncr

int(input())
letters = input().split()
k = int(input())
a = sum(1 for combo in combinations(letters,k) if 'a' in combo)
leng = ncr(len(letters),k)
print (round(a/leng,3))

ValueError: invalid literal for int() with base 10: 'a a a b c'