In [7]:
import numpy

my__1D_array = numpy.array([1, 2, 3, 4, 5])
print(my__1D_array.shape)     #(5,) -> 1 row and 5 columns

(5,)


In [8]:
my__2D_array = numpy.array([[1, 2],[3, 4],[6,5]])
print(my__2D_array.shape)     #(3, 2) -> 3 rows and 2 columns

(3, 2)


In [10]:
import numpy

change_array = numpy.array([1,2,3,4,5,6])
change_array.shape = (3, 2)
print(change_array)

[[1 2]
 [3 4]
 [5 6]]


In [12]:
import numpy

my_array = numpy.array([1,2,3,4,5,6])
print(numpy.reshape(my_array,(3,2)))



[[1 2]
 [3 4]
 [5 6]]


# Task

You are given a space separated list of nine integers. Your task is to convert this list into a X NumPy array.

### Input Format

A single line of input containing  space separated integers.

### Output Format

Print the X NumPy array.



In [35]:
import numpy as np

print(np.reshape(np.array([input().split(" ")]).astype(np.int32),(3,3)))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [34]:
types.dtype

dtype('int32')